### ISSUE TITLE
Translate `tutorial/controlflow.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#103]
This needs to reach 100% translated.

Current stats for tutorial/controlflow.po:

- Fuzzy: 12
- Percent translated: 68%
- Entries: 85 / 124
- Untranslated: 27

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html)

**Comment by a19c** [comment]
Hola buenas noches. Me gustaría empezar a traducir este archivo

**Comment by humitos** [comment]
Adelante!

**Comment by humitos** [comment]
Hecho en #173
