### ISSUE TITLE
Translate `faq/library.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#160]
This needs to reach 100% translated.

Current stats for `faq/library.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 142
- Untranslated: 142

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by sdelquin** [comment]
Me gustaría trabajar en esta issue!

**Comment by humitos** [comment]
Hecho en #214
