### ISSUE TITLE
Translate `reference/introduction.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#165]
This needs to reach 100% translated.

Current stats for `reference/introduction.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 25
- Untranslated: 25

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by srxavi** [comment]
I would like to translate this

**Comment by humitos** [comment]
Yes! You want it, you have it! :smile: Happy translation time!

**Comment by srxavi** [comment]
[Merged](https://github.com/PyCampES/python-docs-es/pull/185)

**Comment by raulcd** [comment]
Solved
