### ISSUE TITLE
Translate `library/urllib.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#199]
This needs to reach 100% translated.

Current stats for `library/urllib.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 7
- Untranslated: 7

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by gomezgleonardob** [comment]
Please assign me

**Comment by humitos** [comment]
Enjoy!

**Comment by gomezgleonardob** [comment]
Hi, this issue is closed on https://github.com/PyCampES/python-docs-es/pull/236
