### ISSUE TITLE
Add sorting dict on Travis builds

### ISSUE THREAD

**Issue by raulcd** [PyCampES/python-docs-es#205]
Add sort of dict to Travis build in order to fail if trying to merge unsorted. Same as pospell/powrap.

**Comment by raulcd** [comment]
@humitos what do you think?

**Comment by humitos** [comment]
I don't think it's _super_ important to block the build because of this really. I don't think it will affect too much on merge conflicts or similar. I do not have a strong opinion, really.

**Comment by raulcd** [comment]
Makes sense we can eventually run it manually every now and then when we feel to. I'll just close it.
