### ISSUE TITLE
Translate `distutils/sourcedist.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#228]
This needs to reach 100% translated.

Current stats for `distutils/sourcedist.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 72
- Untranslated: 72

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by c0x6a** [comment]
I'd like to work on this file :)

**Comment by humitos** [comment]
@c0x6a enjoy translating this file! :partying_face:

**Comment by c0x6a** [comment]
done: https://github.com/PyCampES/python-docs-es/pull/310
