### ISSUE TITLE
Translate `distutils/introduction.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#229]
This needs to reach 100% translated.

Current stats for `distutils/introduction.po`:

- Fuzzy: 0
- Percent translated: 0%
- Entries: 0 / 52
- Untranslated: 52

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/page/CONTRIBUTING.html).

**Comment by katialira** [comment]
Yo me apunto a este :)

**Comment by raulcd** [comment]
Thanks @katialira

**Comment by katialira** [comment]
Este issue se puede cerrar por el [PR 257](https://github.com/PyCampES/python-docs-es/pull/257)

**Comment by humitos** [comment]
Gracias!
