### ISSUE TITLE
Travis builds fallan en rama 3.7 debido a palabras que faltan en diccionario

### ISSUE THREAD

**Issue by raulcd** [PyCampES/python-docs-es#25]
Builds en la rama 3.7 llevan fallando varios días:
https://travis-ci.org/github/raulcd/python-docs-es

```
Sphinx parallel build error:
AttributeError: 'BuildEnvironment' object has no attribute 'note_versionchange'
Makefile:43: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/tmp/cpython/Doc'
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 2
The command "make CPYTHON_CLONE=/tmp/cpython/ COMMIT=15e7d2432294ec46f1ad84ce958fdeb9d4ca78b1" exited with 2.
Done. Your build exited with 1.
```

**Comment by humitos** [comment]
Esto lo arregló @gilgamezh en #26, pero en #27 se vuelve a romper. Ahora no pasa el `pospell` porque hay muchas palabras argentinas (e inglesas) que no existen en el diccionario `-es`.

**Comment by raulcd** [comment]
Hay un archivo dict dónde se pueden poner algunas excepciones, quizás podemos incluir algunas de esas palabras ahí?

**Comment by humitos** [comment]
Sí. Creo que tiene sentido tener un diccionaro con palabras excluídas. También hay palabras que están mal tipeadas. Y, si vamos a mezclar estilos de Español, quizás sea bueno incluír otras variaciones de diccionarios `-es`

**Comment by raulcd** [comment]
Otras ideas a investigar:
Se puede pasar pospell con varios diccionarios `es-ar`, `es-ES`.
Existe un diccionario de hunspell con un español neutro?
Podemos hacer un merge de varios diccionarios y que se utilice ese diccionario?

**Comment by raulcd** [comment]
Se arregló el build aquí:
https://github.com/PyCampES/python-docs-es/pull/96
