### ISSUE TITLE
Mejorar la guía de CONTRIBUTING

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#31]
Tenemos una pequeña guía que explica el procedimiento. Sin embargo, estaría bueno mejorarla un poco para que sea más fácil de seguir para persona que no sepan mucho de github y demás herramientas: https://github.com/raulcd/python-docs-es/blob/3.7/CONTRIBUTING.rst

**Comment by clacri** [comment]
Vale, anoto esto aquí para que no se me olvide pero pondré una sección específica en el contributing, donde podemos añadir, si os parece, un FAQ, o más bien frequently faced problems.... ahaha y poner si acaso las cosas que pueden ocurrir:

En Mac, fallos al intentar make progress que dicen algo de un realpath son 99% posiblemente la falta de una librería, se soluciona haciendo: brew install coreutils

**Comment by raulcd** [comment]
Deberiamos añadir las herramientas para que el build pase:
`powrap`, `pospell`, diccionarios, etc
