### ISSUE TITLE
Traducir `glossary.po`

### ISSUE THREAD

**Issue by marian-vignau** [PyCampES/python-docs-es#47]
El glosario es mencionado innumerables veces desde otros .po

**Comment by hectorcanto** [comment]
En el README.rst hay también un trocito de glosario (no se si tiene la intención de ser un ejemplo o de ser cubierto)

**Comment by humitos** [comment]
Este issue ya está hecho en #53 -- @marian-vignau ¿falta algo más o lo podemos cerrar?

> En el README.rst hay también un trocito de glosario (no se si tiene la intención de ser un ejemplo o de ser cubierto)

Creé un issue para decidir qué en esos casos y agregarlo a la memoria de traducción.

https://github.com/PyCampES/python-docs-es/issues/83
