### ISSUE TITLE
Decidir proceso de "triage" para no pisarnos

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#52]
El grupo está creciendo y necesitamos organizarnos para no traducir dos veces lo mismo y que no se generen conflictos ni que perdamos tiempo repitiendo acciones.

@marcorichetta propuso algo así: https://github.com/reactjs/es.reactjs.org/issues/4#issue-405384115

@marian-vignau propuso hacer un issue por archivo e ir asignándolos a las personas que quieran hacer cada página.

¿Cuál creen que sería el mejor flow para esto? ¿Otras ideas?

Una vez tengamos el flow, deberíamos mencionarlo en el CONTRIBUTING.

**Comment by clacri** [comment]
Ambas opciones me parecen bien, y es cierto que se empieza a necesitar algo así. Una página (.po) por persona es razonable, y a menos que haya algún tipo de priorización (hay cosas que deben ser traducidas antes que otras), el sistema de que cada uno diga que le gustaría traducir y le sea asignado me parece bien. Entiendo que de lo de la priorización, una vez tengamos el tutorial y el glosario, podemos estar en la web de PSF, y ya entonces se trata de ir completando, no?

**Comment by raulcd** [comment]
Para ponerlo en la página oficial deberíamos tener:
tutorial, bugs.po, and library/functions.po.
Aparte deberíamos crear la rama 3.8 y mergear con los cambios que haya.

**Comment by cacrespo** [comment]
Un issue por archivo (o conjunto de archivos) me parece más fácil para los que se quieran sumar.
Junto a la priorización agregaría la posibilidad de marcar de algún modo aquellos casos donde se incluye textos con notas al pie o "adaptaciones" para que se revisen con mayor detenimiento

**Comment by hectorcanto** [comment]
También habría que tener un chat (IRC, RocketChat) o abrir issues (o ambos) para discusiones transversales, por ejemplo, términos con traducciones polémicas/confusas.

**Comment by eamanu** [comment]
Hola, 

Ambas propuestas me parece que están bastantes buenas. No he usado mucho Github,
pero se que se pueden crear boards [0], lo cual nos daría una buena visibilidad
del progreso de las tareas. 

En cuanto a la primera propuesta (la de @marcorichetta) se parece mucho a la que se
aplicó en el debian-med team [1] dónde hay wiki con la lista de Need help y
cada uno podía modificar la wiki, asignandose las tareas y haciendo check cuando
termina.

Por otro lado la propuesta de @marian-vignau  va más de la mano de lo que mencioné
primero un issue por task.

El problema que veo de las propuestas (si es que se las puede llamar problema), es que
también hay que definir como asignar los issues/archivos a aquellas personas que quieren comenzar a traducir, porque me parece que para asignar un issue debe ser a alguien que pertenezca al proyecto. Igualmente si seguimos el modelo [2] hay que mantener actualizado
el issue. 

[0] https://help.github.com/en/github/managing-your-work-on-github/about-project-boards
[1] https://salsa.debian.org/med-team/community/2020-covid19-hackathon/-/wikis/COVID-19-Hackathon-packages-needing-work
[2] https://github.com/reactjs/es.reactjs.org/issues/4

**Comment by humitos** [comment]
Bueno, creo que estamos más o menos todos alineados en que un issue por archivo son más o menos una buena idea. Supongo que podemos empezar por ahí e ir viendo como evoluciona.

Creé un issue que podemos seguir de ejemplo para esto: https://github.com/PyCampES/python-docs-es/issues/64 . Lo agregué a un Milestone, así también nos da una idea de dónde estamos y podemos priorizar por Milestone si lo deseamos.

> También habría que tener un chat (IRC, RocketChat)

Tenemos un canal de Télegram y una lista de correo que podemos utilizar para esto. Sería bueno que cada duda que tengamos con algún término la pongamos en una memoria de traducción. (hice una propuesta para esto en #63

> El problema que veo de las propuestas (si es que se las puede llamar problema), es que
> también hay que definir como asignar los issues/archivos a aquellas personas que quieren comenzar a traducir, porque me parece que para asignar un issue debe ser a alguien que pertenezca al proyecto.

Sí. El que quiere trabajar en el issue, puede dejar un comentario diciendo que lo va a tomar y un admin se lo asigna. De cualquier forma, somos varios los admin del proyecto y siempre podemos agregar más. Creo que esto no va a ser un problema.

**Comment by humitos** [comment]
> Una vez tengamos el flow, deberíamos mencionarlo en el CONTRIBUTING.

Esto parece ser lo último que queda de este issue. Ya tenemos medianamente el proceso funcionando. Me lo asigno para documentarlo cuando tenga un tiempo.
