### ISSUE TITLE
Translate `tutorial/stdlib.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#64]
This file is at 88% translated. It needs to reach 100% translated.

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/es/3.7/CONTRIBUTING.html)

**Comment by eamanu** [comment]
@humitos I would like to work on this file.  Thanks
