### ISSUE TITLE
Translate `library/functions.po`

### ISSUE THREAD

**Issue by erasmo07** [PyCampES/python-docs-es#72]
This file is at 0% translated. It needs to reach 100% translated.

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/es/3.7/CONTRIBUTING.html)

**Comment by erasmo07** [comment]
@raulcd

**Comment by clacri** [comment]
Ya la tenía asignada yo en la issue #61, lo que pasa es que la creé yo antes de que pusierais el sistema en el que habeis escrito el porcentaje y demás. Solo había llegado hasta bytearray class. @erasmo07 , contáctame cuando puedas y lo organizamos para ver si continúas tu o yo y no pisarnos.

**Comment by humitos** [comment]
@erasmo07 perdón por la confusión en este issue. Por favor, busca otro para trabajar. Este archivo ya está asignado a @clacri 

Cierro este issue ya que es un duplicado de #61.
