### ISSUE TITLE
Translate `library/zipimport.po`

### ISSUE THREAD

**Issue by cacrespo** [PyCampES/python-docs-es#74]
This file is at 0% translated. It needs to reach 100% translated.

Please, comment here if you want this file to be assigned to you and a member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/es/3.7/CONTRIBUTING.html)

**Comment by qagustina** [comment]
me pueden asignar?

**Comment by raulcd** [comment]
@cacrespo estabas trabajando en el fichero o le asigno a @qagustina ?

**Comment by humitos** [comment]
@cacrespo hizo `library/zlip.po` en #73 que es otro archivo. Este issue es sobre `library/zipimport.po`. Se lo asigno a @qagustina

**Comment by cacrespo** [comment]
Sí. zlip.po fue el otro que subí. 
Iba a empezar con zipimport.po. Tomo otro, no problem! En cuanto arranco subo el issue correspondiente.

**Comment by humitos** [comment]
@cacrespo fijate que ya hay varios issues creados que puedes agarrar de ahí.

**Comment by humitos** [comment]
Done in #266
