### ISSUE TITLE
Translate `faq/index.po`

### ISSUE THREAD

**Issue by humitos** [PyCampES/python-docs-es#85]
This file is at 0% translated. It needs to reach 100% translated.

Please, comment here if you want this file to be assigned to you and an member will assign it to you as soon as possible, so you can start working on it.

Remember to follow the steps in our [Contributing Guide](https://python-docs-es.readthedocs.io/es/3.7/CONTRIBUTING.html)

**Comment by hectorcanto** [comment]
Please assign it to me

**Comment by hectorcanto** [comment]
merged

**Comment by raulcd** [comment]
Gracias @hectorcanto no me había dado cuenta
